### PR TITLE
Issue-1056 : Updated the models link to errors

### LINKED ISSUE #916: Move remaining models out of portability-types-transfer and into portability-types-common
Theres documentation and content about the Blobby model in portability-types-transfer whereas the rest of the models live in portability-types-common. 

https://github.com/google/data-transfer-project/tree/abb554b604329dcacaa62a8b8c5615f6aa47e0bd/portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/models

https://github.com/google/data-transfer-project/tree/abb554b604329dcacaa62a8b8c5615f6aa47e0bd/portability-types-common/src/main/java/org/datatransferproject/types/common/models

### PR DESCRIPTION
**Pull request by SampathKumarAmex**
Related to issue : https://github.com/google/data-transfer-project/issues/1056

fixes #916

### CODE REVIEW

**Review by seehamrun — APPROVED** [review]

**Comment by seehamrun** [comment]
Thanks for updating the link, can you please sign the CLA so we can merge this?

**Review by jzacsh — CHANGES_REQUESTED** [review]
LGTM aside from the fix to the top of the doc we're touching in this PR. Thanks for doing this!

**Comment by apurvagandhi** [comment]
It seems like the requested changes were not merged and CLA was not signed. Does this issue still requires attention (i.e. should I fix the requested changes) and open another PR for the issue so we are able to merge this to the master?

**Comment by lisad** [comment]
Since this PR is inactive, I'm going to close it out and make a PR myself

**Pull request closed without merging**
