### PR TITLE
fix: upgrade nimbus-jose-jwt to 9.21.1

### PR DESCRIPTION
**Pull request by csankhala**
fix for #1084

### CODE REVIEW

**Comment by csankhala** [comment]
Hi @jzacsh Please review

**Comment by csankhala** [comment]
Hi @seehamrun Please review

**Comment by csankhala** [comment]
I signed CLA. @seehamrun Please do it

**Review by calumcalder — APPROVED** [review]
This is quite a large version jump, but looking at the changelog there don't seem to be any breaking changes that affect our usage.

Thanks @csankhala!

**Pull request merged**
